export type SabangnetOrderField = {
  key: string
  label: string
  /** 실데이터 기반 추정. 몰마다 다를 수 있음 */
  hint?: string
}

/** 사방넷 주문조회 responseItems + 한글명 (문서 search-orders-1 기준) */
export const SABANGNET_ORDER_FIELDS: SabangnetOrderField[] = [
  { key: 'ORDER_DT', label: '주문일시' },
  { key: 'COLLECT_DT', label: '수집일시' },
  { key: 'ORD_CM_DT', label: '주문확인일시' },
  { key: 'REG_DATE', label: '최초등록일시' },
  { key: 'SB_ORD_NO', label: '주문번호' },
  { key: 'SHOP_ORD_NO', label: '쇼핑몰주문번호' },
  { key: 'SHOP_NM', label: '쇼핑몰명' },
  { key: 'SHOP_LOGIN_ID', label: '쇼핑몰접속로그인ID' },
  { key: 'ORDER_STATUS', label: '주문상태코드' },
  { key: 'ORDER_STATUS_NM', label: '주문상태코드명' },
  { key: 'ORD_DIV_CD', label: '주문상태유형구분코드' },
  { key: 'PAY_TOT_AMT', label: '결제합계금액' },
  { key: 'ORDER_TOT_AMT', label: '주문합계금액' },
  { key: 'CT_SALE_COST', label: '판매가(수집)' },
  { key: 'COST_PRICE', label: '원가합계금액' },
  { key: 'REVENUE_CONTRIBUTE_COST', label: '매출기여금' },
  { key: 'CT_DELIVERY_COST', label: '배송비(수집)' },
  { key: 'CHG_DELIVERY_COST', label: '변경배송구분내용' },
  { key: 'ORD_CNT', label: '주문수량' },
  { key: 'CM_EA', label: '단품수량' },
  { key: 'EA', label: '수량(단품묶음개수)' },
  { key: 'CM_PRD_NM', label: '확정상품명' },
  { key: 'CT_PRD_NM', label: '수집상품명' },
  { key: 'PRT_PRD_NM', label: '출력상품명' },
  { key: 'CM_SKU_NM', label: '확정단품명' },
  { key: 'CT_SKU_NM', label: '수집단품명' },
  { key: 'UPD_CT_SKU_NM', label: '수정수집단품명' },
  { key: 'BRAND_NM', label: '브랜드명' },
  { key: 'MODEL_NM', label: '모델명' },
  { key: 'MODEL_NO', label: '모델번호명' },
  { key: 'BARCODE', label: '바코드' },
  { key: 'SB_PRD_CD', label: '상품번호' },
  { key: 'SB_SKU_CD', label: '단품번호' },
  { key: 'SHOP_PRD_CD', label: '쇼핑몰상품코드' },
  { key: 'CUSTOM_PRD_CD', label: '자체상품코드' },
  { key: 'SKU_CD', label: 'SKU코드' },
  { key: 'SKU_ABBR', label: '단품약어명' },
  { key: 'PRD_ABBR', label: '상품약어비고' },
  { key: 'SHOP_SUPPLY_UNIT_PRICE', label: '쇼핑몰공급단가' },
  { key: 'SHOP_ORD_SEQ', label: '쇼핑몰주문중복식별번호2' },
  { key: 'SUB_SHOP_ORD_SEQ', label: '쇼핑몰주문중복식별번호1' },
  { key: 'ORG_SB_ORD_NO', label: '원본주문번호' },
  { key: 'SET_DIV_CD', label: '세트구분코드' },
  { key: 'SET_SPRT_DIV_CD', label: '세트분리주문구분코드' },
  { key: 'CAL_MTHD_YN', label: '정산적용방법구분코드' },
  { key: 'ACNT_REGS_SRNO', label: '계정등록순번' },
  { key: 'BUYER_CD', label: '매입처서비스계정ID' },
  { key: 'BUYER_ID', label: '매입처로그인ID' },
  { key: 'BUYER_NM', label: '매입처서비스계정명' },
  { key: 'LOGISTICS_CD', label: '물류처서비스계정ID' },
  { key: 'LOGISTICS_ID', label: '물류처로그인ID' },
  { key: 'LOGISTICS_NM', label: '물류처서비스계정명' },
  { key: 'LOGISTICS_MSG', label: '물류처배송메시지' },
  { key: 'LOCATION', label: '관리장소명' },
  { key: 'CAT_L_CD', label: '카테고리대분류코드' },
  { key: 'CAT_M_CD', label: '카테고리중분류코드' },
  { key: 'CAT_S_CD', label: '카테고리소분류코드' },
  { key: 'CAT_D_CD', label: '카테고리세분류코드' },
  { key: 'HOPE_DELIVERY_DT', label: '희망배송일' },
  { key: 'RELEASE_CMPL_DT', label: '출고완료일시' },
  { key: 'CANCEL_CMPL_DT', label: '취소완료일시' },
  { key: 'RETURN_CMPL_DT', label: '반품완료일시' },
  { key: 'EXCHANGE_CMPL_DT', label: '교환완료일시' },
  { key: 'WAYBILL_NO', label: '운송장번호' },
  { key: 'WAYBILL_REG_DT', label: '송장등록일시' },
  { key: 'WAYBILL_SEND_DT', label: '운송장송신일시' },
  { key: 'WAYBILL_SEND_ERR_MSG', label: '운송장송신오류메시지' },
  { key: 'PCSCP_CD', label: '택배사코드' },
  { key: 'DELIVERY_MSG', label: '배송메시지' },
  { key: 'DELIVERY_ETC_MSG', label: '배송메시지+주문기타메시지' },
  { key: 'DELIVERY_DIV_NM', label: '배송기타필드값' },
  { key: 'ETC_MSG', label: '주문기타메시지' },
  { key: 'GIFT_FLD_VL', label: '사은품여유필드값' },
  { key: 'FLD_DSP', label: '주문단순출력용도필드값1' },
  { key: 'SUPPLY_CNTR_NO', label: '공급계약번호' },
  { key: 'CUSTOMS_CLEARANCE', label: '통관내용수집필드값' },
  { key: 'CUSTOMS_CLEARANCE_CERT_NO', label: '통관인증번호' },
  { key: 'CONSUMER_ID', label: '주문자ID' },
  { key: 'CONSUMER_NM', label: '주문자명' },
  { key: 'CONSUMER_TEL', label: '주문자전화번호' },
  { key: 'CONSUMER_CEL', label: '주문자핸드폰번호' },
  { key: 'CONSUMER_EMAIL', label: '주문자이메일주소' },
  { key: 'RECEIVER_NM', label: '수취인명' },
  { key: 'RECEIVER_TEL', label: '수취인전화번호' },
  { key: 'RECEIVER_CEL', label: '수취인핸드폰번호' },
  { key: 'RECEIVER_EMAIL', label: '수취인이메일주소' },
  { key: 'RECEIVER_ZIPCODE', label: '수취인우편번호' },
  { key: 'RECEIVER_ADDR', label: '수취인전체주소' },
  { key: 'ETC_FLD_1', label: '주문수집필드값1', hint: '쿠팡: 상품명 · 스마트스토어: 일시코드 · CJ: 주문번호 · 삼성카드: 단문자코드' },
  { key: 'ETC_FLD_2', label: '주문수집필드값2', hint: '스마트스토어: 유입경로 · 쿠팡: 상품/옵션ID · CJ: 긴 숫자ID' },
  { key: 'ETC_FLD_3', label: '주문수집필드값3', hint: '스마트스토어: 결제만료시각 · MakeShop: 배송메모/입금자 · 쿠팡: 0 또는 숫자' },
  { key: 'ETC_FLD_4', label: '주문수집필드값4', hint: 'MakeShop: 금액 · CJ: 「없음」 등 상태문구 · 신세계: 몰명' },
  { key: 'ETC_FLD_5', label: '주문수집필드값5', hint: '스마트스토어: 결제수단 · MakeShop: Y/N 플래그' },
  { key: 'ETC_FLD_6', label: '주문수집필드값6', hint: '쿠팡: 날짜(출고/배송 관련) · 스마트스토어: 숫자ID' },
  { key: 'ETC_FLD_7', label: '주문수집필드값7', hint: '스마트스토어: 옵션코드(예 278_001_3) · 일부 몰: 「일반」' },
  { key: 'ETC_FLD_8', label: '주문수집필드값8', hint: 'MakeShop: 회원등급/전화주문 · 스마트스토어: 숫자코드' },
  { key: 'ETC_FLD_9', label: '주문수집필드값9', hint: 'CJ: 일시 · 스마트스토어/신세계: 숫자코드' },
  { key: 'ETC_FLD_10', label: '주문수집필드값10', hint: '스마트스토어: 쇼핑몰주문번호 형태' },
  { key: 'ETC_FLD_11', label: '주문수집필드값11', hint: '스마트스토어: 주문기기(MOBILE/PC)' },
  { key: 'ETC_FLD_12', label: '주문수집필드값12', hint: '스마트스토어: 금액(추정)' },
  { key: 'ETC_FLD_13', label: '주문수집필드값13', hint: '스마트스토어: 금액(추정)' },
  { key: 'ETC_FLD_14', label: '주문수집필드값14', hint: '몰별 여유필드 · 현재 샘플에서 값 거의 없음' },
  { key: 'ETC_FLD_15', label: '주문수집필드값15', hint: '스마트스토어: 0 고정값 위주' },
  { key: 'ETC_FLD_16', label: '주문수집필드값16', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_17', label: '주문수집필드값17', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_18', label: '주문수집필드값18', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_19', label: '주문수집필드값19', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_20', label: '주문수집필드값20', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_21', label: '주문수집필드값21', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_22', label: '주문수집필드값22', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_23', label: '주문수집필드값23', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_24', label: '주문수집필드값24', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_25', label: '주문수집필드값25', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_26', label: '주문수집필드값26', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_27', label: '주문수집필드값27', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_28', label: '주문수집필드값28', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_29', label: '주문수집필드값29', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
  { key: 'ETC_FLD_30', label: '주문수집필드값30', hint: '몰별 여유필드 · 현재 샘플에서 미사용' },
]

export const SABANGNET_ORDER_FIELD_KEYS = SABANGNET_ORDER_FIELDS.map((field) => field.key)
