-- 수집은 EC2로 옮겼습니다. Supabase cron 은 2026-08-27 에 해제했습니다.
-- select cron.unschedule('collect-daily-kst');
-- 다시 켜지 마세요. 광고·PlusCL 수집은 /opt/channelboard cron 이 담당합니다.
--
-- (아래는 예전 스케줄. 참고용으로만 둠)
-- 매시 정각 KST = 매시 정각 UTC (시차 9시간이라 분·초는 같음)
-- Dashboard → Integrations → Cron 에서 쓰거나, SQL Editor에서 pg_cron 이 열려 있을 때만 실행하세요.

-- select cron.unschedule('collect-daily-kst');
-- select cron.schedule(
--   'collect-hourly-kst',
--   '0 * * * *',
--   $$
--   select net.http_post(
--     url := 'https://<PROJECT-REF>.supabase.co/functions/v1/collect-daily',
--     headers := '{"Content-Type": "application/json", "x-collect-secret": "<COLLECT_SECRET>"}'::jsonb,
--     body := '{}'::jsonb,
--     timeout_milliseconds := 60000
--   );
--   $$
-- );
