import type { ChannelKind, ChannelMeta } from '../adapters/types'

/**
 * 판매 채널 카탈로그. 매출 원장은 사방넷, 물류 재고·주문은 PlusCL.
 * 대시보드는 channel_snapshots 실매출만 보여 줍니다. 목업 숫자는 쓰지 않습니다.
 */
export type CollectorId = 'sabangnet' | 'coupang' | 'none'

export interface ChannelDefinition extends ChannelMeta {
  kind: ChannelKind
  /** 지금 수집하고 대시보드에 보여줄지 */
  enabled: boolean
  collector: CollectorId
  /** 이 채널이 무엇인지 */
  description: string
}

/**
 * 쇼핑 매출은 사방넷 API 3.0. collect-daily / collect-sabangnet 이 channel_snapshots 에 넣는다.
 */
export const CHANNEL_CATALOG: ChannelDefinition[] = [
  {
    id: 'naver',
    kind: 'commerce',
    name: '스마트스토어',
    shortName: 'Naver',
    ticker: 'NVR',
    letter: 'N',
    badge: '#03C75A',
    accent: '#E8F8D8',
    sparkColor: '#4C9A1A',
    enabled: true,
    collector: 'sabangnet',
    description:
      '네이버 스마트스토어. 매출 원장은 사방넷, 물류 주문·재고는 PlusCL. 광고는 src/ads 의 naver_sa / naver_da.',
  },
  {
    id: 'makeshop',
    kind: 'commerce',
    name: '메이크샵',
    shortName: 'Makeshop',
    ticker: 'MKS',
    letter: 'M',
    badge: '#1FA971',
    accent: '#D8F3E7',
    sparkColor: '#2F9E6B',
    enabled: true,
    collector: 'sabangnet',
    description: '메이크샵 자사몰. 매출 원장은 사방넷. 물류는 PlusCL.',
  },
  {
    id: 'coupang',
    kind: 'commerce',
    name: '쿠팡',
    shortName: 'Coupang',
    ticker: 'CPG',
    letter: 'C',
    badge: '#E74C3C',
    accent: '#FCE8DE',
    sparkColor: '#E85D04',
    enabled: true,
    collector: 'sabangnet',
    description: '쿠팡. 매출·주문은 사방넷. 광고비는 마케팅 메뉴의 coupang_sa.',
  },
  {
    id: 'elevenst',
    kind: 'commerce',
    name: '11번가',
    shortName: '11st',
    ticker: '11ST',
    letter: '11',
    badge: '#E60012',
    accent: '#FDECEC',
    sparkColor: '#C0392B',
    enabled: true,
    collector: 'sabangnet',
    description: '11번가. 매출 원장은 사방넷. 물류는 PlusCL.',
  },
  {
    id: 'shoppingnt',
    kind: 'commerce',
    name: '쇼핑엔티',
    shortName: 'ShoppingNT',
    ticker: 'SNT',
    letter: 'NT',
    badge: '#E11D48',
    accent: '#FDE8EE',
    sparkColor: '#BE123C',
    enabled: true,
    collector: 'sabangnet',
    description: '쇼핑엔티. 매출 원장은 사방넷.',
  },
  {
    id: 'ezwel',
    kind: 'commerce',
    name: '현대이지웰',
    shortName: 'Ezwel',
    ticker: 'EZW',
    letter: 'Ez',
    badge: '#0F766E',
    accent: '#D9F3EF',
    sparkColor: '#0F766E',
    enabled: true,
    collector: 'sabangnet',
    description: '현대이지웰. 매출 원장은 사방넷.',
  },
  {
    id: 'gsshop',
    kind: 'commerce',
    name: 'GS shop',
    shortName: 'GS shop',
    ticker: 'GS',
    letter: 'GS',
    badge: '#2563EB',
    accent: '#E0EAFE',
    sparkColor: '#1D4ED8',
    enabled: true,
    collector: 'sabangnet',
    description: 'GS shop. 매출 원장은 사방넷.',
  },
  {
    id: 'cjonstyle',
    kind: 'commerce',
    name: 'CJ온스타일',
    shortName: 'CJ ONSTYLE',
    ticker: 'CJ',
    letter: 'CJ',
    badge: '#111827',
    accent: '#E8E8EC',
    sparkColor: '#111827',
    enabled: true,
    collector: 'sabangnet',
    description: 'CJ온스타일. 매출 원장은 사방넷.',
  },
  {
    id: 'toss',
    kind: 'commerce',
    name: '토스쇼핑',
    shortName: 'Toss',
    ticker: 'TOSS',
    letter: 'Ts',
    badge: '#0064FF',
    accent: '#DCEBFF',
    sparkColor: '#0052D4',
    enabled: true,
    collector: 'sabangnet',
    description: '토스쇼핑. 매출 원장은 사방넷.',
  },
  {
    id: 'nshome',
    kind: 'commerce',
    name: 'NS홈쇼핑',
    shortName: 'NS',
    ticker: 'NS',
    letter: 'NS',
    badge: '#7C3AED',
    accent: '#EDE4FF',
    sparkColor: '#6D28D9',
    enabled: true,
    collector: 'sabangnet',
    description: 'NS홈쇼핑. 매출 원장은 사방넷.',
  },
  {
    id: 'samsungcard',
    kind: 'commerce',
    name: '삼성카드쇼핑',
    shortName: 'Samsung Card',
    ticker: 'SCS',
    letter: 'SC',
    badge: '#1428A0',
    accent: '#E2E6F8',
    sparkColor: '#1428A0',
    enabled: true,
    collector: 'sabangnet',
    description: '삼성카드쇼핑. 매출 원장은 사방넷.',
  },
  {
    id: 'mamitalk',
    kind: 'commerce',
    name: '마미톡',
    shortName: 'Mamitalk',
    ticker: 'MMT',
    letter: 'Mm',
    badge: '#DB2777',
    accent: '#FCE7F3',
    sparkColor: '#BE185D',
    enabled: true,
    collector: 'sabangnet',
    description: '마미톡. 매출 원장은 사방넷.',
  },
  {
    id: 'benefia',
    kind: 'commerce',
    name: '베네피아',
    shortName: 'Benefia',
    ticker: 'BNF',
    letter: 'Bn',
    badge: '#C2410C',
    accent: '#FFEDD5',
    sparkColor: '#C2410C',
    enabled: true,
    collector: 'sabangnet',
    description: '베네피아. 매출 원장은 사방넷.',
  },
  {
    id: 'mallpie',
    kind: 'commerce',
    name: 'Mallpie',
    shortName: 'Mallpie',
    ticker: 'MLP',
    letter: 'Mp',
    badge: '#0891B2',
    accent: '#CFFAFE',
    sparkColor: '#0E7490',
    enabled: true,
    collector: 'sabangnet',
    description: 'Mallpie. 매출 원장은 사방넷.',
  },
  {
    id: 'lottehome',
    kind: 'commerce',
    name: '롯데홈쇼핑',
    shortName: 'Lotte HS',
    ticker: 'LHS',
    letter: 'LH',
    badge: '#E11D48',
    accent: '#FEE2E2',
    sparkColor: '#BE123C',
    enabled: true,
    collector: 'sabangnet',
    description: '롯데홈쇼핑. 매출 원장은 사방넷.',
  },
  {
    id: 'gmarket',
    kind: 'commerce',
    name: 'ESM지마켓',
    shortName: 'Gmarket',
    ticker: 'GMKT',
    letter: 'Gm',
    badge: '#00D094',
    accent: '#D1FAE5',
    sparkColor: '#059669',
    enabled: true,
    collector: 'sabangnet',
    description: 'ESM 지마켓. 매출 원장은 사방넷.',
  },
  {
    id: 'shinsegae',
    kind: 'commerce',
    name: '신세계몰',
    shortName: 'Shinsegae',
    ticker: 'SSG',
    letter: 'Sg',
    badge: '#C4A35A',
    accent: '#F6F0E0',
    sparkColor: '#A8843D',
    enabled: true,
    collector: 'sabangnet',
    description: '신세계몰. 매출 원장은 사방넷.',
  },
  {
    id: 'homeandshopping',
    kind: 'commerce',
    name: '홈&쇼핑',
    shortName: 'Home&Shopping',
    ticker: 'HNS',
    letter: 'HS',
    badge: '#EA580C',
    accent: '#FFEDD5',
    sparkColor: '#C2410C',
    enabled: true,
    collector: 'sabangnet',
    description: '홈&쇼핑. 매출 원장은 사방넷.',
  },
  {
    id: 'musinsa',
    kind: 'commerce',
    name: '무신사',
    shortName: 'Musinsa',
    ticker: 'MSS',
    letter: 'Ms',
    badge: '#111111',
    accent: '#E8E8E8',
    sparkColor: '#111111',
    enabled: true,
    collector: 'sabangnet',
    description: '무신사. 매출 원장은 사방넷.',
  },
  {
    id: 'ably',
    kind: 'commerce',
    name: '에이블리',
    shortName: 'Ably',
    ticker: 'ABL',
    letter: 'Ab',
    badge: '#7C3AED',
    accent: '#EDE4FF',
    sparkColor: '#6D28D9',
    enabled: true,
    collector: 'sabangnet',
    description: '에이블리. 매출 원장은 사방넷.',
  },
  {
    id: 'halfclub',
    kind: 'commerce',
    name: '하프클럽',
    shortName: 'Halfclub',
    ticker: 'HFC',
    letter: 'Hf',
    badge: '#1E3A8A',
    accent: '#DBEAFE',
    sparkColor: '#1D4ED8',
    enabled: true,
    collector: 'sabangnet',
    description: '하프클럽. 매출 원장은 사방넷.',
  },
  {
    id: 'instagram',
    kind: 'sns',
    name: '인스타그램',
    shortName: 'Instagram',
    ticker: 'IG',
    letter: 'Ig',
    badge: '#E1306C',
    accent: '#F6E6F0',
    sparkColor: '#C13584',
    enabled: false,
    collector: 'none',
    description: '인스타그램. 수집기 미구현.',
  },
  {
    id: 'youtube',
    kind: 'sns',
    name: '유튜브',
    shortName: 'YouTube',
    ticker: 'YT',
    letter: 'Yt',
    badge: '#FF0000',
    accent: '#FDE2E2',
    sparkColor: '#E11D48',
    enabled: false,
    collector: 'none',
    description: '유튜브. 수집기 미구현.',
  },
  {
    id: 'kakao',
    kind: 'sns',
    name: '카카오',
    shortName: 'Kakao',
    ticker: 'KKO',
    letter: 'Kk',
    badge: '#3C1E1E',
    accent: '#FFF6C8',
    sparkColor: '#C9A227',
    enabled: false,
    collector: 'none',
    description: '카카오. 수집기 미구현.',
  },
  {
    id: 'blog',
    kind: 'sns',
    name: '블로그',
    shortName: 'Blog',
    ticker: 'BLG',
    letter: 'Bl',
    badge: '#2D6AE3',
    accent: '#E4EEFF',
    sparkColor: '#3B6DCC',
    enabled: false,
    collector: 'none',
    description: '블로그. 수집기 미구현.',
  },
]

export function enabledChannels(): ChannelDefinition[] {
  return CHANNEL_CATALOG.filter((channel) => channel.enabled)
}

export function getChannel(id: string): ChannelDefinition | undefined {
  return CHANNEL_CATALOG.find((channel) => channel.id === id)
}

export function isChannelEnabled(id: string): boolean {
  return getChannel(id)?.enabled === true
}

export function enabledChannelIds(): string[] {
  return enabledChannels().map((channel) => channel.id)
}

/** 예전 윙 계정 자리(쿠팡 1/2)는 사방넷 쿠팡 하나로 합친다. */
export function canonicalChannelId(id: string): string {
  if (id === 'coupang_1' || id === 'coupang_2') return 'coupang'
  return id
}

export function definitionForChannel(id: string, displayName?: string): ChannelDefinition {
  const known = getChannel(id)
  if (known) return known
  const name = displayName?.trim() || id
  const letter = [...name][0] ?? '?'
  return {
    id,
    kind: 'commerce',
    name,
    shortName: name,
    ticker: id.replace(/^sb_/i, '').slice(0, 6).toUpperCase() || 'SB',
    letter,
    badge: '#64748B',
    accent: '#E2E8F0',
    sparkColor: '#475569',
    enabled: true,
    collector: 'sabangnet',
    description: `${name}. 매출 원장은 사방넷.`,
  }
}
