export type PageId =
  | 'dashboard'
  | 'channels'
  | 'commerce'
  | 'stock'
  | 'marketing'
  | 'settlement'
  | 'reports'
  | 'tutorial'
  | 'pagetest'
  | 'devlab'
  | 'apicheck'
  | 'accounts'
  | 'menu'
