import type { GridColumnDef } from './types'
import type { PageTestGridRow } from '../../../pages/pageTest/gridRows'
import { pageTestCategoryOptions } from '../../../pages/pageTest/gridRows'

export function pageTestGridColumns(): GridColumnDef<PageTestGridRow>[] {
  return [
    {
      id: 'thumbnail',
      label: '썸네일',
      width: 72,
      kind: 'thumbnail',
      pin: 'left',
      sortable: false,
      defaultVisible: false,
      getValue: (row) => row.thumbnail,
    },
    {
      id: 'sku',
      label: 'SKU',
      width: 108,
      kind: 'text',
      pin: 'left',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.sku,
      getSortValue: (row) => row.sku,
    },
    {
      id: 'name',
      label: '상품명',
      width: 220,
      minWidth: 140,
      kind: 'text',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.name,
      getSortValue: (row) => row.name,
    },
    {
      id: 'brand',
      label: '브랜드',
      width: 128,
      kind: 'text',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.brand,
      getSortValue: (row) => row.brand,
    },
    {
      id: 'status',
      label: 'Status',
      width: 120,
      kind: 'status',
      sortable: true,
      defaultVisible: false,
      getValue: (row) => row.status,
      getSortValue: (row) => row.status,
    },
    {
      id: 'progress',
      label: '진행률',
      width: 140,
      kind: 'progress',
      sortable: true,
      defaultVisible: false,
      getValue: (row) => row.progress,
      getSortValue: (row) => row.progress,
    },
    {
      id: 'trend',
      label: 'Trend',
      width: 108,
      kind: 'sparkline',
      sortable: false,
      defaultVisible: true,
      getValue: (row) => row.trend,
    },
    {
      id: 'qty',
      label: '재고',
      width: 88,
      kind: 'number',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.qty,
      getSortValue: (row) => row.qty,
    },
    {
      id: 'expireDate',
      label: '유통기한',
      width: 108,
      kind: 'text',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.expireDate,
      getSortValue: (row) => row.expireDate,
    },
    {
      id: 'remainingDays',
      label: '잔여일',
      width: 88,
      kind: 'number',
      sortable: true,
      defaultVisible: false,
      getValue: (row) => row.remainingDays ?? -1,
      getSortValue: (row) => row.remainingDays ?? -1,
    },
    {
      id: 'warehouse',
      label: '창고',
      width: 96,
      kind: 'text',
      sortable: true,
      defaultVisible: false,
      getValue: (row) => row.warehouse,
      getSortValue: (row) => row.warehouse,
    },
    {
      id: 'category',
      label: '카테고리',
      width: 120,
      kind: 'editable-select',
      sortable: true,
      defaultVisible: false,
      options: pageTestCategoryOptions(),
      getValue: (row) => row.category,
      getSortValue: (row) => row.category,
    },
    {
      id: 'note',
      label: '비고',
      width: 160,
      minWidth: 120,
      kind: 'editable-text',
      sortable: true,
      defaultVisible: true,
      getValue: (row) => row.note,
      getSortValue: (row) => row.note,
    },
  ]
}
